#!/usr/bin/env bash
# Configure nginx to add the X-Served-By HTTP header with the server hostname
set -e

export DEBIAN_FRONTEND=noninteractive

sudo apt-get update -y
sudo apt-get install -y nginx

echo "add_header X-Served-By \"$HOSTNAME\";" | sudo tee /etc/nginx/conf.d/custom_header.conf

sudo nginx -t
sudo service nginx restart
